#!/usr/bin/env bash

docker compose exec -T app bash -c "vendor/bin/phpstan analyse -c phpstan.dist.neon" || exit 1

CHANGED_FILES=$(git diff --cached  --name-only --diff-filter=ACM -- '*.php' | tr '\n' ' ')
if [ -n "$CHANGED_FILES" ]; then
   docker compose exec -T app bash -c "vendor/bin/php-cs-fixer fix --config .php-cs-fixer.dist.php $CHANGED_FILES; git add $CHANGED_FILES;"
fi