services:
  php:
    image: php-app
    container_name: php-app-local
    restart: unless-stopped
    volumes:
      - php-app-caddy-data:/data
      - php-app-caddy-config:/config
      - ./:/app/
    environment:
      SYMFONY_VERSION: 7.2.*
      STABILITY: stable
      APP_ENV: local
      XDEBUG_MODE: debug
    ports:
      - target: 80
        published: ${HTTP_PORT:-8088}
        protocol: tcp
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database-app
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: toor
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    volumes:
      - app-db-data:/var/lib/postgresql/data

volumes:
  php-app-caddy-data:
  php-app-caddy-config:
  app-db-data: